### ISSUE TITLE
The ability is self-triggering.

### ISSUE THREAD

**Issue by yeaktas** [fleizean/ft_transcendence#111]
When you use the "Frozen Ball" ability, the "Fast and Furious" ability is used automatically.

**Comment by fleizean** [comment]
bakılacak ama sanmıyorum frozen ball kullanınca belirli bir süre top donuyor aslında bu da bir taktik olabilir tam topu dondurduğunda bu yeteneği kullanmak karşı tarafın bunu algılamayarak beklenmedik hızla gelmesine yol açar güzel zorlaştırıcı bir şey olur.

**Comment by fleizean** [comment]
solved
