### ISSUE TITLE
End game screen or exit.

### ISSUE THREAD

**Issue by yeaktas** [fleizean/ft_transcendence#113]
![Image](https://github.com/fleizean/ft_transcendence/assets/96894640/95e655cc-39b3-4dda-9ec1-ec7f9fcd0b90)

**Comment by fleizean** [comment]
<img width="657" alt="Ekran Resmi 2024-02-20 18 36 59" src="https://github.com/fleizean/ft_transcendence/assets/66090171/07cecac9-b7fb-4f31-b576-d3e4c33c2cee">
orginal pong game bu şekilde buna benzer bir şey yapılmalı @temasictfic

**Comment by fleizean** [comment]
solved

<img width="904" alt="Ekran Resmi 2024-02-20 19 10 48" src="https://github.com/fleizean/ft_transcendence/assets/66090171/e9c67be0-7c34-418d-b812-7900702db159">
