### ISSUE TITLE
Ranking kazanma yüzdesine göre sıralıyor.

### ISSUE THREAD

**Issue by yeaktas** [fleizean/ft_transcendence#116]
Pong pointe göre sıralamanın belirlenmesi gerekmiyor mu?

![Image](https://github.com/fleizean/ft_transcendence/assets/96894640/72a1a167-6a6b-4468-bfe5-b58309a5e746)

**Comment by fleizean** [comment]
Hayır elo point aynı win-rate sahip olduğu durumda devreye girer.

**Comment by yeaktas** [comment]
Rankingsi Pong pointe göre sıralayacak şekilde değiştirdim fakat profile_vivewste istediğim sonucu alamadım. Kontrol eder misiniz?

**Comment by fleizean** [comment]
i think solved
