### ISSUE TITLE
Sound Errors

### ISSUE THREAD

**Issue by fleizean** [fleizean/ft_transcendence#127]
DOM yapısı mantığı yüzünden oyuna ilk girişte klavye girişi olmazsa autoplay özelliği çalışmıyor; Bu yüzden çözüm olarak kişinin giriş ekranında Space tuşuna basarak oyuna başlamasını yaptırarak 3'den geriye sayarak oyunu başlatabiliriz hemde konsept güzelleşir.

"Tarayıcılar, kullanıcının etkileşimde bulunmadığı bir web sayfasında otomatik olarak ses oynatılmasını engelleyebilir."

**Comment by yeaktas** [comment]
Bu durumla ilgileneceğim.
