### ISSUE TITLE
Info for Website

### ISSUE THREAD

**Issue by fleizean** [fleizean/ft_transcendence#169]

**Comment by yeaktas** [comment]
[WORK IN PROGRESS]

![Image](https://github.com/fleizean/ft_transcendence/assets/96894640/77f9ef59-b30b-4f98-9bb2-68712df8ca27)


Giriş ekranı için artık şöyle bir info modalız var. Diğer modallar yapım aşamasında.

**Comment by fleizean** [comment]
Indian-Pong'a diye düzeltirsek harika olmuş eline sağlık

**Comment by fleizean** [comment]
<img width="1169" alt="Ekran Resmi 2024-03-09 22 06 24" src="https://github.com/fleizean/ft_transcendence/assets/66090171/57488178-c5ef-4533-8460-6e3e6b6094ae">
<img width="1279" alt="Ekran Resmi 2024-03-09 22 06 31" src="https://github.com/fleizean/ft_transcendence/assets/66090171/71bdc20b-3742-45c1-a4f2-7a4b14b4cdda">

Play-ai'a tasarımı koruyarak game-info butonuyla beraber bilgilerle ekledim.
