### ISSUE TITLE
Follow not working

### ISSUE THREAD

**Issue by yeaktas** [fleizean/ft_transcendence#174]

**Comment by fleizean** [comment]
![image](https://github.com/fleizean/ft_transcendence/assets/66090171/f61fd17c-0546-4aac-9074-a96cbcc8b688)
çalışmıyor çünkü backend tarafında isteğin gelişine bakılırken follow unfollow diye actiona bakılıyor bu durumlar ise innerhtml ierçisinde yazan yani bizim localizationda verdiğimiz değer oluyor farklı bir yöntemle yapılması gerek benim yazdığım bir kod değil.

**Comment by fleizean** [comment]
yine de çözüldü
