### ISSUE TITLE
SPA

### ISSUE THREAD

**Issue by yeaktas** [fleizean/ft_transcendence#28]
When will we start the SPA version??!?

**Comment by yeaktas** [comment]
nvm

**Comment by fyurtsev** [comment]
I think we start this week

**Comment by fleizean** [comment]
> I think we start this week
<img width="137" alt="Ekran Resmi 2024-02-01 01 10 59" src="https://github.com/fleizean/ft_transcendence/assets/66090171/42d7f8eb-38a9-47af-80b0-ebe620d5ef0b">
