### ISSUE TITLE
Fotoğrafsız kullanıcı ve kullanıcı arama hakkında.

### ISSUE THREAD

**Issue by yeaktas** [fleizean/ft_transcendence#71]
Kullanıcı fotoğrafsız olarak giriş yaptığında zaten default bir fotoğraf ekliyoruz. Öyleyse neden search.html içerisinde böyle bir kontrol yapmamız gerekiyor. 

>                         {% if kullanici.avatar %}
>                             <a href="/profile/{{kullanici.username}}" class="go-profile"><img class="round" src="{{kullanici.avatar.url}}" width="156px" height="156px"
>                                 alt="user" /></a>
>                         {% else %}
>                             <a href="/profile/{{kullanici.username}}" class="go-profile"><img class="round" src="/static/assets/profile/profilephoto.jpeg"
>                                 alt="user" width="128px" height="128px"/></a>
>                         {% endif %}

**Comment by fleizean** [comment]
we are doing because when i wrote this code we had no default image record for db. i will remove this code when i click vscode

**Comment by yeaktas** [comment]
I deleted this code and it gave an error. That's why I opened this question.

Btw, you can write the code like this;
`<img src="{% if kullanici.avatar %}{{kullanici.avatar.url}}{% else %}/static/assets/profile/profilephoto.jpeg{% endif %}" alt="Avatar" class="profile-img">`

**Comment by fleizean** [comment]
i dont know django tricks, and u said the default photo was saved in db. if you get an error after deleting it, it means it's not being added db.
