### ISSUE TITLE
Minor Module: Support on all devices.

### ISSUE THREAD

**Issue by yeaktas** [fleizean/ft_transcendence#72]
> Kullanıcıların, kullandıkları cihaza bağlı olarak dokunmatik ekran, klavye ve fare gibi farklı giriş yöntemlerini kullanarak web sitesinde kolayca gezinebilmelerini ve web sitesiyle etkileşimde bulunabilmelerini sağlayın.

Oyun oynamak için de geçerli mi olması gerekiyor?

**Comment by fleizean** [comment]
yep its meaning responsive but we dont do that right now

**Comment by yeaktas** [comment]
हम यह मॉड्यूल नहीं करेंगे.
