### ISSUE TITLE
Fotoğraflar basık görünüyor.

### ISSUE THREAD

**Issue by yeaktas** [fleizean/ft_transcendence#74]
[Şöyle bir şey varmış](https://www.w3schools.com/css/css3_object-fit.asp)

@fleizean

**Comment by yeaktas** [comment]
![image](https://github.com/fleizean/ft_transcendence/assets/96894640/22abdea1-c11b-49c3-bb17-c83564637425)

Bruh

**Comment by fleizean** [comment]
solved
