### ISSUE TITLE
Major Module: Introduce an AI Opponent.

### ISSUE THREAD

**Issue by yeaktas** [fleizean/ft_transcendence#83]
AI modülünde şu maddeyi incelememiz gerekiyor:

> The AI must replicate human behavior, meaning that in your AI implementation, you must simulate keyboard input. The constraint here is that the AI can only refresh its view of the game once per second, requiring it to anticipate bounces and other actions.

> The AI must utilize power-ups if you have chosen to implement the Game customization options module.

**Comment by fleizean** [comment]
solved
